//! `bindings`: Rust runtime bindings for a linked entry; no selection, no native compilation.
use crate::{load_program, options};
use seismic_lang::repr;
use seismic_lang::sir::{Definition, Program};
use seismic_lang::sym::Sym;
use seismic_lang::types::Elem;
use seismic_lang::types::{Extent, Ty};

/// Any definition in a family can name the entry ABI because family construction checks
/// every implementation against the same contract.
fn abi_definition<'a>(program: &'a Program, entry: &str) -> Result<&'a Definition, String> {
    let family = program.resolve_family(entry)?;
    family
        .bodies
        .iter()
        .chain(&family.lowerings)
        .map(|id| program.definition(*id))
        .next()
        .ok_or_else(|| format!("linked function `{entry}` has no implementation"))
}

/// A symbolic extent as a Rust expression over the fields of the shapes struct `s`.
fn rustify(s: &Sym) -> String {
    let mut out = String::new();
    let mut ident = String::new();
    for ch in s.to_string().chars().chain(std::iter::once(' ')) {
        if ch.is_alphanumeric() || ch == '_' {
            ident.push(ch);
            continue;
        }
        if !ident.is_empty() {
            if !ident.starts_with(|c: char| c.is_ascii_digit()) {
                out.push_str("s.");
            }
            out.push_str(&ident);
            ident.clear();
        }
        out.push(ch);
    }
    format!("({})", out.trim_end())
}

/// A shapes struct, an arguments struct holding buffers and scalars, byte sizes per tensor
/// plane, and the `Bindings` implementation the runtime consumes.
pub fn bindings(args: &[String]) -> Result<(), String> {
    let o = options(args, &["--fn", "--element"])?;
    let (_, program) = load_program(&o)?;
    let name = o.entry()?;
    let f = abi_definition(&program, name)?;
    let camel: String = name
        .split('_')
        .map(|w| {
            let mut c = w.chars();
            c.next().map_or(String::new(), |h| {
                h.to_uppercase().collect::<String>() + c.as_str()
            })
        })
        .collect();
    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by `seismic bindings` for `{name}` from {}. Do not edit.\n",
        program.files[f.file].0
    ));
    out.push_str("#![allow(non_snake_case, dead_code)]\nuse seismic_runtime::plan::Bindings;\nuse seismic_runtime::Buffer;\nuse std::collections::HashMap;\n\n");
    out.push_str("/// A packed tensor's planes on the device.\npub struct Packed {\n    pub planes: HashMap<String, Buffer>,\n}\n\n");
    out.push_str(&format!(
        "#[derive(Clone, Copy, Debug)]\npub struct {camel}Shapes {{\n"
    ));
    for p in &f.shape_params {
        out.push_str(&format!("    pub {p}: i64,\n"));
    }
    out.push_str("}\n\n");
    out.push_str(&format!("impl {camel}Shapes {{\n    pub fn map(&self) -> HashMap<String, i64> {{\n        let mut m = HashMap::new();\n"));
    for p in &f.shape_params {
        out.push_str(&format!(
            "        m.insert(\"{p}\".to_string(), self.{p});\n"
        ));
    }
    out.push_str("        m\n    }\n}\n\n");
    out.push_str(&format!("pub struct {camel}<'a> {{\n"));
    let mut sizes = Vec::new();
    let mut buffer_arms = Vec::new();
    let mut scalar_arms = Vec::new();
    for param in &f.params {
        let pname = &param.name;
        match &param.ty {
            Ty::Tensor(s) => {
                let axes = s
                    .axes
                    .iter()
                    .map(|axis| match axis {
                        Extent::Semantic(sym) => Ok(sym),
                        Extent::Structural(_) => Err(format!("parameter `{pname}` has a structural extent; entry storage is semantic")),
                    })
                    .collect::<Result<Vec<_>, String>>()?;
                let product = |skip: Option<usize>| {
                    axes.iter()
                        .enumerate()
                        .filter(|(i, _)| Some(*i) != skip)
                        .fold(Sym::constant(1), |a, (_, d)| a.mul(d))
                };
                let elem = match &s.elem {
                    Elem::Param(p) => o.workload.elems.get(p).ok_or_else(|| {
                        format!(
                            "parameter `{pname}` has generic element `{p}`; bind it with --element"
                        )
                    })?,
                    concrete => concrete,
                };
                match elem {
                    Elem::Dtype(d) => {
                        out.push_str(&format!("    pub {pname}: &'a Buffer,\n"));
                        sizes.push(format!(
                            "        (\"{pname}\", \"\", ({} * {}) as usize),",
                            rustify(&product(None)),
                            d.bytes()
                        ));
                        buffer_arms.push(format!(
                            "            (\"{pname}\", \"\") => Some(self.{pname}),"
                        ));
                    }
                    Elem::Repr(r) => {
                        let rep = repr::lookup(r)
                            .ok_or_else(|| format!("unknown representation `{r}`"))?;
                        let packed = s.packed_axis.ok_or_else(|| {
                            format!("packed parameter `{pname}` has no packed axis")
                        })?;
                        let values = axes
                            .get(packed)
                            .ok_or_else(|| format!("packed axis of `{pname}` is out of range"))?;
                        out.push_str(&format!("    pub {pname}: &'a Packed,\n"));
                        for plane in rep.planes() {
                            sizes.push(format!(
                                "        (\"{pname}\", \"{}\", ({} * {} * {}) as usize),",
                                plane.name,
                                rustify(&product(Some(packed))),
                                rustify(&plane.extent(values)),
                                plane.dtype().bytes()
                            ));
                            buffer_arms.push(format!("            (\"{pname}\", \"{}\") => self.{pname}.planes.get(\"{}\"),", plane.name, plane.name));
                        }
                    }
                    Elem::Param(p) => {
                        return Err(format!("element binding of `{p}` is not concrete"))
                    }
                }
            }
            ty @ (Ty::Scalar(_) | Ty::Index(_)) => {
                let integer =
                    matches!(ty, Ty::Index(_)) || matches!(ty, Ty::Scalar(d) if d.is_int());
                out.push_str(&format!(
                    "    pub {pname}: {},\n",
                    if integer { "i64" } else { "f64" }
                ));
                scalar_arms.push(format!(
                    "            \"{pname}\" => Some(self.{pname} as f64),"
                ));
            }
            other => {
                return Err(format!(
                    "parameter `{pname}` of type {other} has no binding"
                ))
            }
        }
    }
    out.push_str("}\n\n");
    out.push_str(&format!("impl<'a> {camel}<'a> {{\n    /// Byte size of every tensor plane: (parameter, plane, bytes).\n    pub fn sizes(s: &{camel}Shapes) -> Vec<(&'static str, &'static str, usize)> {{\n        vec![\n{}\n        ]\n    }}\n}}\n\n", sizes.join("\n")));
    out.push_str(&format!("impl<'a> Bindings for {camel}<'a> {{\n    fn buffer(&self, root: &str, plane: &str) -> Option<&Buffer> {{\n        match (root, plane) {{\n{}\n            _ => None,\n        }}\n    }}\n\n    fn scalar(&self, name: &str) -> Option<f64> {{\n        match name {{\n{}\n            _ => None,\n        }}\n    }}\n}}\n", buffer_arms.join("\n"), scalar_arms.join("\n")));
    print!("{out}");
    Ok(())
}
