//! Logical plan inspection and runtime ABI bindings; no native compilation.
use crate::{load_program, options};
use seismic_lang::{repr, types::{Elem, Ty}};
pub fn plan(args: &[String]) -> Result<(), String> {
    let o = options(args)?;
    let program = load_program(&o)?;
    let name = o.function.as_ref().ok_or("--fn is required")?;
    let plan = seismic_lang::plan::plan_specialized(&program, name, &o.shapes, &o.elements)?;
    let mut distinct = std::collections::BTreeMap::new();
    for (i, step) in plan.steps.iter().enumerate() {
        let mut shapes: Vec<String> = step.shapes.iter().map(|(k, v)| format!("{k}={v}")).collect();
        shapes.sort();
        *distinct.entry(format!("{}[{}]", step.kernel, shapes.join(","))).or_insert(0usize) += 1;
        let tensors: Vec<String> = step.tensors.iter().map(|t| if t.elem_offset == 0 { format!("{}={}", t.param, t.root) } else { format!("{}={}+{}", t.param, t.root, t.elem_offset) }).collect();
        let scalars: Vec<String> = step.scalars.iter().map(|(n, s)| match s {
            seismic_lang::plan::ScalarSource::Literal(x) => format!("{n}={x}"),
            seismic_lang::plan::ScalarSource::Param(p) => format!("{n}=<{p}>"),
        }).collect();
        println!("{i:4}: {}({}{}{})", step.kernel, tensors.join(", "), if scalars.is_empty() { "" } else { ", " }, scalars.join(", "));
    }
    println!("{} step(s), {} distinct kernel instantiation(s):", plan.steps.len(), distinct.len());
    for (k, n) in distinct {
        println!("  {n:4} x {k}");
    }
    Ok(())
}

/// Rust bindings for a composition function: a shapes struct, an arguments struct holding
/// buffers and scalars, byte sizes per tensor part, and the `Bindings` implementation the
/// automatically selected runtime consumes.
pub fn bindings(args: &[String]) -> Result<(), String> {
    let o = options(args)?;
    if !o.elements.is_empty() {return Err("bindings generator does not yet accept concrete element substitutions".into());}
    let program = load_program(&o)?;
    let name = o.function.as_ref().ok_or("--fn is required")?;
    let f = program.functions.iter().find(|f| &f.name == name).ok_or_else(|| format!("no function `{name}`"))?;
    let camel: String = name.split('_').map(|w| { let mut c = w.chars(); match c.next() { Some(h) => h.to_uppercase().collect::<String>() + c.as_str(), None => String::new() } }).collect();
    let rustify = |s: &seismic_lang::sym::Sym| -> String {
        let text = format!("{s}");
        let mut out = String::new();
        let mut ident = String::new();
        for ch in text.chars().chain(std::iter::once(' ')) {
            if ch.is_alphanumeric() || ch == '_' {
                ident.push(ch);
            } else {
                if !ident.is_empty() {
                    if ident.chars().next().unwrap().is_ascii_digit() { out.push_str(&ident); } else { out.push_str("s."); out.push_str(&ident); }
                    ident.clear();
                }
                out.push(ch);
            }
        }
        format!("({})", out.trim_end())
    };
    let mut out = String::new();
    out.push_str(&format!("// Generated by `seismic bindings` for `{name}`. Do not edit.\n"));
    out.push_str("#![allow(non_snake_case, dead_code)]\nuse seismic_runtime::plan::Bindings;\nuse seismic_runtime::Buffer;\nuse std::collections::HashMap;\n\n");
    out.push_str("/// A packed tensor's parts on the device.\npub struct Packed {\n    pub planes: HashMap<String, Buffer>,\n}\n\n");
    out.push_str(&format!("#[derive(Clone, Copy, Debug)]\npub struct {camel}Shapes {{\n"));
    for p in &f.shape_params {
        out.push_str(&format!("    pub {p}: i64,\n"));
    }
    out.push_str("}\n\n");
    out.push_str(&format!("impl {camel}Shapes {{\n    pub fn map(&self) -> HashMap<String, i64> {{\n        let mut m = HashMap::new();\n"));
    for p in &f.shape_params {
        out.push_str(&format!("        m.insert(\"{p}\".to_string(), self.{p});\n"));
    }
    out.push_str("        m\n    }\n}\n\n");
    out.push_str(&format!("pub struct {camel}<'a> {{\n"));
    let mut sizes = Vec::new();
    let mut buffer_arms = Vec::new();
    let mut scalar_arms = Vec::new();
    for (pname, ty) in &f.params {
        match ty {
            Ty::Tensor(s) => {
                let rows: seismic_lang::sym::Sym = s.shape[..s.shape.len() - 1].iter().fold(seismic_lang::sym::Sym::constant(1), |a, d| a.mul(d));
                let last = s.shape.last().unwrap().clone();
                match &s.elem {
                    Elem::Dtype(d) => {
                        out.push_str(&format!("    pub {pname}: &'a Buffer,\n"));
                        sizes.push(format!("        (\"{pname}\", \"\", ({} * {} * {}) as usize),", rustify(&rows), rustify(&last), d.bytes()));
                        buffer_arms.push(format!("            (\"{pname}\", \"\") => Some(self.{pname}),"));
                    }
                    Elem::Repr(r) => {
                        let rep = repr::lookup(r).unwrap();
                        out.push_str(&format!("    pub {pname}: &'a Packed,\n"));
                        for plane in rep.planes() {
                            sizes.push(format!("        (\"{pname}\", \"{}\", ({} * {} * {}) as usize),", plane.name, rustify(&rows), rustify(&plane.extent(&last)), plane.dtype().bytes()));
                            buffer_arms.push(format!("            (\"{pname}\", \"{}\") => self.{pname}.planes.get(\"{}\"),", plane.name, plane.name));
                        }
                    }
                    Elem::Param(p) => return Err(format!("parameter `{pname}` has generic element `{p}`")),
                }
            }
            Ty::Scalar(d) => {
                let rust = if d.is_int() { "i64" } else { "f64" };
                out.push_str(&format!("    pub {pname}: {rust},\n"));
                scalar_arms.push(format!("            \"{pname}\" => Some(self.{pname} as f64),"));
            }
            other => return Err(format!("parameter `{pname}` of type {other} has no binding")),
        }
    }
    out.push_str("}\n\n");
    out.push_str(&format!("impl<'a> {camel}<'a> {{\n    /// Byte size of every tensor part: (parameter, part, bytes).\n    pub fn sizes(s: &{camel}Shapes) -> Vec<(&'static str, &'static str, usize)> {{\n        vec![\n{}\n        ]\n    }}\n}}\n\n", sizes.join("\n")));
    out.push_str(&format!("impl<'a> Bindings for {camel}<'a> {{\n    fn buffer(&self, root: &str, part: &str) -> Option<&Buffer> {{\n        match (root, part) {{\n{}\n            _ => None,\n        }}\n    }}\n\n    fn scalar(&self, name: &str) -> Option<f64> {{\n        match name {{\n{}\n            _ => None,\n        }}\n    }}\n}}\n", buffer_arms.join("\n"), scalar_arms.join("\n")));
    print!("{out}");
    Ok(())
}
