export { connect, makeClientLayer, protocolLayer, protocolLayerWithRecovery, AcnClientTag } from "./protocol"
export type { AcnClient } from "./protocol"

export { DaemonSpawnerTag } from "./daemon-spawner"
export type { DaemonSpawner } from "./daemon-spawner"
export { makeLocalDaemonSpawner, type SpawnProcess, type LocalSpawnerOptions } from "./local-spawner"
export { makeRemoteDaemonSpawner } from "./remote-spawner"
export {
  makeAcnJitRuntime,
  type AcnJitRuntime,
  type AcnJitRuntimeOptions,
} from "./acn-jit/acn-recovering-client"

export { TracingLayer, makeTracingLayer, type MakeTracingLayerOptions } from "./tracing"

export {
  DisplayState as DisplayStateSchema,
  DisplayTimeline as DisplayTimelineSchema,
  DisplayViewSnapshot,
  DisplayViewShape as DisplayViewShapeSchema,
  MagnitudeRpcs,
  StreamEvent as StreamEventSchema,
  canonicalExtensionForImageMediaType,
  filenameWithImageExtension,
  forkIdToKey,
  imageMediaTypeFromFilename,
  imageMediaTypeFromMime,
  isSupportedImageFilename,
  ProviderModelCatalogLifecycle,
  ProviderModelCatalogLoading,
  ProviderModelCatalogReady,
  ProviderModelCatalogRefreshing,
  ProviderModelCatalogDegraded,
  ProviderModelCatalogUnavailable,
  LocalModelInventoryLifecycle,
  LocalModelInventoryEntryLifecycle,
  LocalModelInventoryLoading,
  LocalModelInventoryReady,
  LocalModelInventoryFailed,
  LocalModelAvailableForDownload,
  LocalModelDownloading,
  LocalModelDownloaded,
  LocalModelDownloadFailed,
  ModelSlotLifecycle,
  ModelSlotUnassigned,
  ModelSlotUnloadedLocalModel,
  ModelSlotLoadingLocalModel,
  ModelSlotReady,
  ModelSlotUnloadingLocalModel,
  ModelSlotBlocked,
  SlotIdSchema,
  LocalModelIdSchema,
  LocalInferenceAcceleratorIdSchema,
  LocalInferenceMemoryDomainIdSchema,
  PercentageSchema,
  ModelCapabilitiesSchema,
  ModelFailureSchema,
  LocalModelFitSchema,
  ProviderModelCatalogStateSchema,
  LocalModelInventoryStateSchema,
  LocalModelInventoryEntrySchema,
  LocalModelInventoryEntryDetailsSchema,
  ProviderCatalogEntrySchema,
  ProviderModelCatalogEntrySchema,
  SlotSelectionSchema,
  ModelSlotBlockedReasonSchema,
  ModelSlotSchema,
  LocalInferenceAcceleratorSchema,
  LocalInferenceMemoryDomainSchema,
  ModelSlotsStateSchema,
  LocalInferenceHardwareSchema,
  PRIMARY_SLOT_ID,
  SECONDARY_SLOT_ID,
  MODEL_SLOT_IDS,
  ProviderModelCatalogMirror,
  ModelSlotsMirror,
  LocalInferenceHardwareMirror,
  LocalModelInventoryMirror,
} from "@magnitudedev/protocol"

export type {
  AgentCommunicationMessage,
  RawClipboardImageAttachment,
  CreateSessionInitial,
  DisplayActor,
  DisplayActorWork,
  DisplayActivity,
  DisplayAttachment,
  DisplayMessage,
  DisplayState,
  DisplayTasks,
  DisplayTimeline,
  DisplayTimelineEntry,
  DisplayTimelinePresentation,
  DisplayTimelinePresentationMode,
  DisplayTimelineStatusSlot,
  DisplayTimelineWindowShape,
  DisplayTimelineWindowInfo,
  DisplayViewShape,
  DisplayMessageTimelineEntry,
  DisplayToolSummaryTimelineEntry,
  DisplayToolStepTimelineEntry,
  DirectoryCandidate,
  ErrorDisplayMessage,
  RawFileImageAttachment,
  RawImageAttachment,
  RawMentionOccurrence,
  ImageAttachment,
  ImageMediaType,
  InterruptedMessage,
  ListSessionsResult,
  MentionCandidate,
  MentionAttachment,
  MentionDirectoryAttachment,
  MentionFileAttachment,
  MentionFileRangeAttachment,
  MentionContentType,
  MentionLineRange,
  MessageAttachment,
  PendingInboundCommunication,
  SearchDirectoriesResult,
  SearchMentionsResult,
  SessionCwdSummary,
  SessionMetadata,
  SessionOptions,
  StreamEvent,
  TaskAssignee,
  TaskDisplayRow,
  TimelineActivity,
  ToolMessage,
  ToolStepPresentation,
  ToolSummaryPresentation,
  ToolPhase,
  ToolTone,
  ToolIcon,
  ToolDiffHunk,
  ToolDiffSlot,
  ToolFileRef,
  ToolSummaryDetailItem,
  ShellPresentation,
  FileWritePresentation,
  FileEditPresentation,
  FileReadPresentation,
  FileSearchPresentation,
  FileTreePresentation,
  FileViewPresentation,
  WebSearchPresentation,
  WebFetchPresentation,
  SkillPresentation,
  CheckpointPresentation,
  SpawnWorkerPresentation,
  GenericToolPresentation,
  QueryImagePresentation,
} from "@magnitudedev/protocol"
export type * from "@magnitudedev/protocol"

export { createRoles, isRoleId, ROLE_IDS, ROLE_TO_SLOT, DEFAULT_REASONING_EFFORT, SLOT_IDS, SLOT_DISPLAY_NAMES, SLOT_DESCRIPTIONS } from "@magnitudedev/roles"
export type { RoleId } from "@magnitudedev/roles"

export { resolveBinaryCommand, defaultBinaryPath, defaultDataDir, type ResolveBinaryOptions, type ResolvedBinaryCommand } from "./binary"
export { SDK_VERSION } from "./version"
export {
  NoDaemon,
  DaemonSpawnFailed,
  BinaryNotFound,
  BinaryVersionMismatch,
  RegistrationFileInvalid,
  DownloadFailed,
  ChecksumMismatch,
  DaemonCrashed,
  DaemonError,
  type StreamDisplayViewFailure,
  type WatchFileFailure,
} from "./errors"

export { isEnvFlagOn } from "@magnitudedev/utils"
export { normalizeReferencedPath } from "./path-utils"

// =============================================================================
// Provider client surface — the sole provider boundary for agent & ACN
// =============================================================================

export {
  ProviderClient,
  createProviderClient,
  type ProviderClientShape,
  type ProviderClientConfig,
  type ProviderRegistryInfo,
  type ProviderRuntimeConfig,
  type ProviderCatalogOutcome,
  type ProviderRejection,
  type ProviderClientError,
  type BaseCallOptions,
  type ModelDiscoveryOperationId,
  type ModelPropertyDiscoveryError,
  type ModelPropertyDiscoveryRequest,
  type ModelPropertyName,
  type ReasoningEffort,
  type ProviderModelBindOptions,
  type ProviderModel,
  type ProviderModelAvailability,
  type ProviderModelDisabledReason,
  type ProviderId,
  type ProviderModelId,
  type ModelFamilyId,
  AVAILABLE_PROVIDER_MODEL,
  isProviderModelAvailable,
  ModelCatalogError,
  ProviderIdSchema,
  ProviderModelIdSchema,
  ModelFamilyIdSchema,
  ProviderModelAvailabilitySchema,
  ProviderModelSchema,
  ModelDiscoveryOperationIdSchema,
  ModelPropertyDiscoveryErrorSchema,
  ModelPropertyDiscoveryRequestSchema,
  ModelPropertyNameSchema,
  ReasoningEffortSchema,
  ReasoningProperty,
  VisionProperty,
  type MagnitudeModelInfo,
  type MagnitudeCallOptions,
  type MagnitudeAdditionalOptions,
  type WebSearchResult,
  type WebSearchError,
  type UsageQuery,
  type CloudUsageResponse,
  type FetchUsageOptions,
  type UsagePeriod,
  makeFileBackedModelCatalog,
  createMagnitudeCompatibleSpec,
  MagnitudeModelListResponseSchema,
  toMagnitudeModelInfo,
  classifyMagnitudeRejectedResponse,
  classifyModelFamilyFromEvidence,
  tryParseErrorBody,
  type ParsedMagnitudeApiError,
} from "./provider-client"

export {
  type ToolCallId,
  type ChatCompletionsStreamChunk,
  type StreamFailure,
  type StreamStartFailure,
  type Prompt,
  type ToolDefinition,
  StreamOperationalFailure,
  StreamProviderError,
  StreamProviderCorrectnessViolation,
  StreamClientCorrectnessViolation,
  StreamStartClientCorrectnessViolation,
  StreamStartProviderCorrectnessViolation,
  StreamStartOperationalFailure,
  acceptedHttpResponse,
  payloadSample,
  rejectedHttpResponse,
  streamStartFailureFromRejectedResponse,
  toCauseInfo,
  nativeChatCompletionsCodec,
} from "@magnitudedev/ai"
