export const MAGNITUDE_SERVICE_ORIGIN = "http://127.0.0.1:10100"
export const MAGNITUDE_INFERENCE_BASE_URL = `${MAGNITUDE_SERVICE_ORIGIN}/inference/`
export const MAGNITUDE_ANTHROPIC_BASE_URL =
  `${MAGNITUDE_SERVICE_ORIGIN}/inference/anthropic`
