import { FileSystem } from "@effect/platform"
import { Effect, Layer, Schema } from "effect"
import { posix } from "node:path"
import { AssertionFailure, InfrastructureFailure } from "./domain"
import { SystemElf, SystemElfResolver } from "./elf-dependency-closure"
import { inspectNativeImage } from "./native-image"
import { command, ProcessExecutor } from "./process"

export const LoaderCacheEntry = Schema.Struct({ name: Schema.NonEmptyString, abi: Schema.NonEmptyString, path: Schema.NonEmptyString })
const fail = (message: string) => new AssertionFailure({ message: `System ELF resolution: ${message}` })
const systemPath = (path: string) => posix.normalize(path) === path
  && /^\/(?:usr\/)?lib(?:64)?\//.test(path)

export const decodeLoaderCache = (output: string) => Effect.gen(function* () {
  const lines = output.trim().split("\n")
  const count = /^(\d+) libs found in cache `[^`]+['`]$/.exec(lines[0] ?? "")?.[1]
  if (count === undefined || Number(count) > 65_536) return yield* fail("invalid or oversized loader-cache header")
  const entries: (typeof LoaderCacheEntry.Type)[] = []
  for (const line of lines.slice(1)) {
    if (!line.trim() || /^Cache generated by: /.test(line)) continue
    const match = /^\s+(\S+) \(([^)]+)\) => (\/[^\r\n]+)$/.exec(line)
    if (!match) return yield* fail("malformed loader-cache entry")
    entries.push({ name: match[1]!, abi: match[2]!, path: match[3]! })
  }
  if (entries.length !== Number(count)) return yield* fail("truncated loader-cache listing")
  return entries
})

/** Deliberately fail closed on cache ambiguity rather than guess hwcap/loader priority. */
export const systemElfResolver = (manager: "deb" | "rpm", allowedNames: readonly string[]) => Layer.effect(SystemElfResolver, Effect.gen(function* () {
  const fs = yield* FileSystem.FileSystem
  const processes = yield* ProcessExecutor
  const run = (program: string, args: readonly string[]) => command(program, args, {
    env: { PATH: "/usr/sbin:/usr/bin:/sbin:/bin", LC_ALL: "C" }, inheritEnv: false, timeoutMs: 30_000, maxOutputBytes: 8 * 1024 * 1024,
  }).pipe(Effect.provideService(ProcessExecutor, processes))
  const entries = yield* Effect.cached(Effect.gen(function* () {
    const output = yield* run("/sbin/ldconfig", ["-p"])
    if (output.exitCode !== 0) return yield* new InfrastructureFailure({ operation: "loader-cache", message: "Unable to read guest loader cache" })
    return yield* decodeLoaderCache(output.stdout)
  }))
  return { resolve: (name, arch) => Effect.gen(function* () {
    if (!allowedNames.includes(name) || !/^[A-Za-z0-9_.+-]+$/.test(name)) return yield* fail(`library is not an admitted OS dependency: ${name}`)
    const matching = (yield* entries).filter(entry => entry.name === name
      && (arch === "x64" ? /(?:^|,)x86-64(?:,|$)/.test(entry.abi) : /(?:^|,)AArch64(?:,|$)/.test(entry.abi)))
    if (matching.length !== 1) return yield* fail(`no unique architecture-matching loader-cache entry for ${name}`)
    const entry = matching[0]!
    if (!systemPath(entry.path)) return yield* fail(`loader cache resolves ${name} outside OS library directories`)
    const path = yield* fs.realPath(entry.path)
    if (!systemPath(path) || (yield* fs.stat(path)).type !== "File") return yield* fail(`resolved library escapes OS directories: ${name}`)
    const image = yield* inspectNativeImage(path).pipe(Effect.provideService(FileSystem.FileSystem, fs))
    if (image.format !== "elf" || !image.architectures.includes(arch)) return yield* fail(`resolved library has wrong architecture: ${name}`)
    const owner = yield* run(manager === "deb" ? "/usr/bin/dpkg-query" : "/usr/bin/rpm", manager === "deb"
      ? ["--search", path] : ["-qf", "--qf", "%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}\\n", path])
    if (owner.exitCode !== 0) return yield* fail(`resolved library is not owned by an installed package: ${path}`)
    let packageName: string
    if (manager === "deb") {
      const suffix = `: ${path}`
      const records = owner.stdout.trim().split("\n")
      if (records.length !== 1 || !records[0]!.endsWith(suffix)) return yield* fail(`ambiguous package owner for ${path}`)
      packageName = records[0]!.slice(0, -suffix.length)
      if (!/^[a-z0-9][a-z0-9+.-]*(?::[a-z0-9_-]+)?$/.test(packageName)) return yield* fail(`invalid package owner for ${path}`)
      const status = yield* run("/usr/bin/dpkg-query", ["--show", "--showformat=${db:Status-Status}", packageName])
      if (status.exitCode !== 0 || status.stdout.trim() !== "installed") return yield* fail(`OS dependency package is not installed: ${packageName}`)
    } else {
      packageName = owner.stdout.trim()
      if (!/^[A-Za-z0-9][A-Za-z0-9+._~-]*$/.test(packageName)) return yield* fail(`ambiguous package owner for ${path}`)
    }
    return SystemElf.make({ path, package: packageName })
  }).pipe(Effect.mapError(error => error._tag === "AssertionFailure" || error._tag === "InfrastructureFailure" ? error
    : new InfrastructureFailure({ operation: "system-elf", message: error.message }))) } satisfies SystemElfResolver
}))
