/**
 * Fetch chat templates from HuggingFace for all models in the manifest.
 *
 * Reads MODEL_MANIFEST from model-manifest.ts, fetches templates,
 * generates template files and the canonical-model-registry.ts file.
 *
 * Usage: cd packages/providers && bun run scripts/fetch-templates.ts
 */

import { mkdir, writeFile } from 'node:fs/promises'
import { join, dirname } from 'node:path'

// ── Manifest (inline to avoid build-time import issues) ──────────────────
// This must stay in sync with src/model/model-manifest.ts
const MANIFEST = [
  { id: "kimi-k2.5", name: "Kimi K2.5", family: "kimi", hfRepo: "moonshotai/Kimi-K2.5" },
  { id: "kimi-k2.6", name: "Kimi K2.6", family: "kimi", hfRepo: "moonshotai/Kimi-K2.6" },
  { id: "glm-4.7", name: "GLM-4.7", family: "glm", hfRepo: "zai-org/GLM-4.7" },
  { id: "glm-5", name: "GLM-5", family: "glm", hfRepo: "zai-org/GLM-5" },
  { id: "glm-5.1", name: "GLM-5.1", family: "glm", hfRepo: "zai-org/GLM-5.1" },
  { id: "minimax-m2.5", name: "MiniMax M2.5", family: "minimax", hfRepo: "MiniMaxAI/MiniMax-M2.5" },
  { id: "minimax-m2.7", name: "MiniMax M2.7", family: "minimax", hfRepo: "MiniMaxAI/MiniMax-M2.7" },
] as const

// ── Paths ────────────────────────────────────────────────────────────────
const ROOT = join(import.meta.dir, '..')
const SRC = join(ROOT, 'src')
const TEMPLATES_DIR = join(SRC, 'model', 'generated', 'templates')
const REGISTRY_PATH = join(SRC, 'model', 'generated', 'canonical-model-registry.ts')

// ── Fetch logic ──────────────────────────────────────────────────────────
async function fetchTemplate(hfRepo: string): Promise<string> {
  // Try tokenizer_config.json first (chat_template field)
  const configUrl = `https://huggingface.co/${hfRepo}/raw/main/tokenizer_config.json`
  console.log(`  Trying ${configUrl}`)
  const configResp = await fetch(configUrl)
  if (configResp.ok) {
    const config = await configResp.json() as any
    if (config.chat_template) {
      // chat_template can be a string or an array of {name, template} objects
      if (typeof config.chat_template === 'string') {
        return config.chat_template
      }
      if (Array.isArray(config.chat_template)) {
        // Use the default template (no name) or the first one
        const defaultTemplate = config.chat_template.find((t: any) => !t.name) ?? config.chat_template[0]
        if (defaultTemplate?.template) {
          return defaultTemplate.template
        }
      }
    }
    console.log(`  ⚠ chat_template not found in tokenizer_config.json`)
  } else {
    console.log(`  ⚠ tokenizer_config.json not available (${configResp.status})`)
  }

  // Fallback: try chat_template.jinja directly
  const jinjaUrl = `https://huggingface.co/${hfRepo}/raw/main/chat_template.jinja`
  console.log(`  Trying ${jinjaUrl}`)
  const jinjaResp = await fetch(jinjaUrl)
  if (jinjaResp.ok) {
    return await jinjaResp.text()
  }

  throw new Error(`Could not fetch template for ${hfRepo}: tokenizer_config.json had no chat_template and chat_template.jinja returned ${jinjaResp.status}`)
}

// ── Code generation ──────────────────────────────────────────────────────
function toImportName(id: string): string {
  // kimi-k2.5 → kimiK25Template, glm-4.7 → glm47Template, minimax-m2.7 → minimaxM27Template
  // Convert hyphen-dot-separated ID to camelCase, then add Template suffix
  return id.replace(/[-.](.)/g, (_, c) => c.toUpperCase()) + 'Template'
}

function generateRegistry(entries: { id: string; name: string; family: string; hfRepo: string; importName: string }[]): string {
  const imports = entries.map(e =>
    `import ${e.importName} from './templates/${e.id}/chat_template.jinja' with { type: "text" }`
  ).join('\n')

  const models = entries.map(e =>
    `  { id: "${e.id}" as const, name: "${e.name}", family: "${e.family}", hfRepo: "${e.hfRepo}", template: ${e.importName} },`
  ).join('\n')

  return `// AUTO-GENERATED by fetch-templates.ts — do not edit manually
import type { Model, ModelId } from '../canonical-model'
${imports}

export const MODELS: readonly Model[] = [
${models}
]

export function getModel(modelId: ModelId): Model | undefined {
  return MODELS.find(m => m.id === modelId)
}

export function hasModel(modelId: ModelId): boolean {
  return MODELS.some(m => m.id === modelId)
}
`
}

// ── Main ─────────────────────────────────────────────────────────────────
async function main() {
  console.log('Fetching chat templates from HuggingFace...\n')

  const results: { id: string; name: string; family: string; hfRepo: string; importName: string; template: string }[] = []

  for (const entry of MANIFEST) {
    console.log(`Fetching template for ${entry.id} (${entry.hfRepo})...`)
    try {
      const template = await fetchTemplate(entry.hfRepo)
      const importName = toImportName(entry.id)

      // Write template file
      const templateDir = join(TEMPLATES_DIR, entry.id)
      await mkdir(templateDir, { recursive: true })
      await writeFile(join(templateDir, 'chat_template.jinja'), template, 'utf-8')
      console.log(`  ✓ Saved to src/templates/${entry.id}/chat_template.jinja`)

      results.push({ ...entry, importName, template })
    } catch (err) {
      console.error(`  ✗ FAILED: ${err}`)
      process.exit(1)
    }
  }

  // Generate registry
  console.log('\nGenerating canonical-model-registry.ts...')
  const registryCode = generateRegistry(results)
  await writeFile(REGISTRY_PATH, registryCode, 'utf-8')
  console.log(`  ✓ Saved to src/model/canonical-model-registry.ts`)

  console.log(`\nDone! Fetched ${results.length} templates.`)
}

main().catch(err => {
  console.error('Fatal error:', err)
  process.exit(1)
})
