#!/usr/bin/env python3
"""Offline maintainer tool; native execution embeds PTX and never calls this script."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import tempfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--clang", default="clang")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent
    manifest = json.loads((root / "musl-1.2.5/source.json").read_text())
    for name, digest in manifest["files"].items():
        if hashlib.sha256((root / "musl-1.2.5" / name).read_bytes()).hexdigest() != digest:
            raise RuntimeError(f"pinned math source changed: {name}")
    version = subprocess.check_output([args.clang, "--version"], text=True)
    if "clang version 18.1.3" not in version:
        raise RuntimeError("requalification required for a different offline compiler")
    flags = ["-target", "nvptx64-nvidia-cuda", "-march=sm_80", "-Xclang", "-target-feature", "-Xclang", "-ptx83", "-Xclang", "-target-feature", "-Xclang", "+ptx70", "-S", "-O2", "-ffp-contract=off", "-fno-fast-math", "-fno-builtin", "-nostdinc", "-Ibuild-headers", "portable_math.c"]
    with tempfile.TemporaryDirectory() as temporary:
        target = Path(temporary) / "math.ptx"
        subprocess.run([args.clang, *flags, "-o", str(target)], cwd=root, check=True)
        ptx = target.read_text()
    for directive in [".version 7.0", ".target sm_80", ".address_size 64"]:
        if ptx.count(directive) != 1:
            raise RuntimeError(f"unexpected generated PTX target: {directive}")
        ptx = ptx.replace(directive, "")
    if ".extern" in ptx or ".ftz" in ptx or "fma." in ptx:
        raise RuntimeError("unexpected external dependency, FTZ or contraction")
    output = "// Generated by generate.py from pinned musl 1.2.5; see THIRD_PARTY.md.\n" + ptx
    (root / "portable_math.ptx").write_text(output)
    inputs = [root / "portable_math.c", *sorted((root / "build-headers").glob("*.h"))]
    (root / "generation.json").write_text(json.dumps({
        "compiler": version, "flags": flags,
        "adapter_sha256": {str(p.relative_to(root)): hashlib.sha256(p.read_bytes()).hexdigest() for p in inputs},
        "ptx_sha256": hashlib.sha256(output.encode()).hexdigest(),
    }, indent=2) + "\n")


if __name__ == "__main__":
    main()
