export const ACTIONS_OPEN = '<actions>'
export const ACTIONS_CLOSE = '</actions>'
export const COMMS_OPEN = '<comms>'
export const COMMS_CLOSE = '</comms>'
export const LENSES_OPEN = '<lenses>'
export const LENSES_CLOSE = '</lenses>'

export const TURN_CONTROL_NEXT = '<next/>'
export const TURN_CONTROL_YIELD = '<yield/>'
export const TURN_CONTROL_FINISH = '<finish/>'
