[package]
name = "seismic-cuda"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
magnitude-solver = { path = "../../../solver" }
seismic-lang.workspace = true
seismic-compiler.workspace = true
cranelift-codegen = "=0.125.4"
libloading = "0.8.9"

seismic-realization.workspace = true
seismic-accounting.workspace = true

[dev-dependencies]
seismic-std.workspace = true
