[workspace]
resolver = "2"
members = [
  "solver",
  "solver/lab",
  "engine",
  "templates",
  "seismic-std",
  "seismic/crates/seismic-lang",
  "seismic/crates/seismic-metal",
  "seismic/crates/seismic-cpu",
  "seismic/crates/seismic-cuda",
  "seismic/crates/seismic-cli",
  "seismic/crates/seismic-compiler",
  "seismic/crates/seismic-runtime",
  "seismic/crates/seismic",
  "seismic/crates/seismic-build",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "UNLICENSED"

[workspace.dependencies]
serde = { version = "=1.0.229", features = ["derive"] }
seismic-std = { path = "seismic-std" }
seismic-lang = { path = "seismic/crates/seismic-lang" }
seismic-metal = { path = "seismic/crates/seismic-metal" }
seismic-cpu = { path = "seismic/crates/seismic-cpu" }
seismic-cuda = { path = "seismic/crates/seismic-cuda" }
seismic-compiler = { path = "seismic/crates/seismic-compiler" }
seismic-runtime = { path = "seismic/crates/seismic-runtime" }
seismic = { path = "seismic/crates/seismic" }
seismic-build = { path = "seismic/crates/seismic-build" }

[profile.dev]
debug = "line-tables-only"

[profile.release]
debug = 1
