"""Magnitensor: composable inference tensors compiled through TileLang."""

from .compiler.compilation import (
    CompilationPlan,
    CompiledFunction,
    CompileOptions,
    analyze,
    compile,
    materialize,
)
from .compiler.lowering import (
    Candidate,
    Capabilities,
    LoweringRegistry,
    MatrixInstruction,
    lowerings,
)
from .compiler.tuning import TuningDatabase, TuningKey, TuningRecord
from .kernels import register_builtin_lowerings
from .representations import (
    Affine,
    Code,
    Codebook,
    CodeInterpretation,
    Dense,
    DirectCoefficients,
    HierarchicalCoefficients,
    TensorRepresentation,
)
from .runtime.resources import CapacityError, Completion, Device, Execution, Resource
from .runtime.tilelang import TileLangRuntime
from .tensor.graph import Effects, Graph, Node, Value, ValueKind
from .tensor.operation import (
    NumericalContract,
    Operation,
    evaluate_reference,
    operation,
    operations,
)
from .tensor.ops import (
    add,
    attention_prepare,
    cast,
    causal_attention,
    concatenate,
    decode_bfloat16,
    delta_recurrence,
    divide,
    embedding,
    exp,
    gated_delta_recurrence,
    kv_append,
    kv_copy,
    linear,
    matmul,
    multiply,
    overlay_rows,
    quantized_import,
    recurrent_prepare,
    reshape,
    rms_norm,
    rotary,
    route_topk,
    routed_experts,
    row_dot,
    sample,
    scalar,
    sigmoid,
    silu,
    softmax,
    subtract,
    take_rows,
    tanh,
    transpose,
)
from .tensor.tracing import Argument, Signature, Tensor, trace
from .tensor.types import DENSE, Dim, DType, Layout, TensorSpec

register_builtin_lowerings(lowerings)


def device(target="auto", *, budget_bytes: int, ordinal: int = 0) -> Device:
    return Device(TileLangRuntime(target, ordinal=ordinal), budget_bytes=budget_bytes)


__all__ = [
    "Affine",
    "Argument",
    "Candidate",
    "Capabilities",
    "CapacityError",
    "Code",
    "CodeInterpretation",
    "Codebook",
    "CompileOptions",
    "CompilationPlan",
    "CompiledFunction",
    "Completion",
    "DENSE",
    "DType",
    "Dense",
    "Device",
    "Dim",
    "DirectCoefficients",
    "Effects",
    "Execution",
    "Graph",
    "HierarchicalCoefficients",
    "Layout",
    "LoweringRegistry",
    "MatrixInstruction",
    "Node",
    "NumericalContract",
    "Operation",
    "Resource",
    "Signature",
    "Tensor",
    "TensorRepresentation",
    "TensorSpec",
    "TileLangRuntime",
    "TuningDatabase",
    "TuningKey",
    "TuningRecord",
    "Value",
    "ValueKind",
    "add",
    "analyze",
    "attention_prepare",
    "cast",
    "causal_attention",
    "compile",
    "concatenate",
    "decode_bfloat16",
    "delta_recurrence",
    "device",
    "divide",
    "embedding",
    "evaluate_reference",
    "exp",
    "gated_delta_recurrence",
    "kv_append",
    "kv_copy",
    "linear",
    "lowerings",
    "matmul",
    "materialize",
    "multiply",
    "overlay_rows",
    "quantized_import",
    "operation",
    "operations",
    "reshape",
    "recurrent_prepare",
    "rms_norm",
    "sample",
    "row_dot",
    "rotary",
    "route_topk",
    "routed_experts",
    "scalar",
    "sigmoid",
    "silu",
    "softmax",
    "subtract",
    "take_rows",
    "tanh",
    "trace",
    "transpose",
]
