// Shared geometry for content and its loading presentation. Keep responsive changes here.
export const pageLayout = {
  hardwarePhoto: "min-w-0 overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900",
  hardwareGrid: "grid-cols-[140px_minmax(0,1fr)] min-[1000px]:grid-cols-[220px_minmax(0,1fr)]",
  recommendationRow: "flex min-h-16 w-full items-center gap-3 rounded-xl border px-3 py-4 text-left",
  modelCard: "rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-750 dark:bg-slate-850",
  modelRow: "grid items-center gap-4 lg:grid-cols-[minmax(0,1fr)_auto]",
  recommendations: "grid overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-750 dark:bg-slate-850 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]",
  recommendationList: "space-y-2 p-3",
  recommendationPane: "min-w-0 border-t border-slate-200 p-5 dark:border-slate-750 lg:border-l lg:border-t-0",
  recommendationToolbar: "mb-4 flex flex-wrap items-center justify-between gap-3",
  statusStack: "mt-7 space-y-6",
  statusHero: "relative overflow-hidden rounded-2xl border border-blue-200 bg-gradient-to-br from-blue-50 to-white p-7 dark:border-slate-700 dark:from-slate-800 dark:to-slate-900",
  card: "rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-750 dark:bg-slate-850",
  settingsCard: "mt-6 rounded-lg border border-slate-300 bg-white px-5 py-5 dark:border-slate-750 dark:bg-slate-850",
  catalogToolbar: "mb-5 mt-8 flex flex-wrap items-center justify-between gap-4",
  hardware: "relative my-6 overflow-hidden rounded-2xl border border-blue-200 bg-gradient-to-br from-blue-50 via-white to-slate-100 p-6 dark:border-slate-700 dark:from-slate-800 dark:via-slate-850 dark:to-slate-900",
  harnessCard: "rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-750 dark:bg-slate-850",
  harnessGrid: "grid items-start gap-5 xl:grid-cols-2",
  usageTokens: "grid gap-5 min-[1100px]:grid-cols-3",
  usageTiming: "grid gap-5 min-[900px]:grid-cols-2",
} as const
