import { useState } from "react"
import { Result, useAtomValue } from "@effect-atom/atom-react"
import { Option } from "effect"
import { ServingModelId, type ServingUsageSnapshot } from "@magnitudedev/sdk"
import { useAgentClient, useLocalModels, formatLocalModelDisplayName } from "@magnitudedev/client-common"
import { Gauge, Timer, ArrowDown, ArrowUp, Layers3 } from "lucide-react"

const number = (value: number) => value.toLocaleString()
const decimal = (value: number) => value.toLocaleString(undefined, { maximumFractionDigits: 1 })
export function ServingUsage() {
  const [period, setPeriod] = useState<"Today" | "AllTime">("Today")
  const [model, setModel] = useState("")
  const client = useAgentClient()
  const result = useAtomValue(client.Models.GetServingUsage({ period, timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone, model: model ? Option.some(ServingModelId.make(model)) : Option.none() })).result
  const catalog = useLocalModels()
  const names = Result.isSuccess(catalog) ? new Map(catalog.value.models.map(model => [String(model.modelId), formatLocalModelDisplayName(model)])) : new Map<string, string>()
  const snapshot = Result.isSuccess(result) ? result.value : null
  return <section aria-label="Local usage" className="rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-750 dark:bg-slate-850">
    <div className="flex flex-wrap items-center justify-between gap-4">
      <div><h2 className="font-heading text-lg">Local usage</h2><p className="mt-1 text-sm text-slate-500">What your models have been doing.</p></div>
      <div className="flex flex-wrap items-center gap-3">
        <div className="flex rounded-lg bg-slate-100 p-1 dark:bg-slate-900" aria-label="Usage period">
          {(["Today", "AllTime"] as const).map(value => <button key={value} aria-pressed={period === value} onClick={() => setPeriod(value)} className={`rounded-md px-3 py-1.5 text-sm ${period === value ? "bg-white text-blue-700 shadow-sm dark:bg-slate-750 dark:text-blue-300" : "text-slate-500"}`}>{value === "Today" ? "Today" : "All time"}</button>)}
        </div>
        <select aria-label="Usage model" value={model} onChange={event => setModel(event.target.value)} className="max-w-[240px] rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-900">
          <option value="">All models</option>
          {snapshot?._tag === "Available" && snapshot.models.map(item => <option key={item.id} value={item.id}>{names.get(item.id) ?? item.id}</option>)}
          {model && (snapshot?._tag !== "Available" || !snapshot.models.some(item => item.id === model)) && <option value={model}>{names.get(model) ?? model}</option>}
        </select>
      </div>
    </div>
    {snapshot?._tag === "Available" ? <UsageFigures usage={snapshot} /> : <p className="mt-6 text-sm text-slate-500">{snapshot?._tag === "Unavailable" ? snapshot.message : Result.isFailure(result) ? "Usage history is unavailable. Reconnecting…" : "Reading usage history…"}</p>}
  </section>
}
export function UsageFigures({ usage }: { usage: Extract<ServingUsageSnapshot, { _tag: "Available" }> }) {
  const missingCache = usage.requests - usage.cachedInputRequests
  const metrics = [
    { label: "Input tokens", value: number(usage.inputTokens), icon: ArrowDown, note: "Includes cached input" },
    { label: "Cached input", value: usage.cachedInputRequests === 0 && usage.requests > 0 ? "—" : number(usage.cachedInputTokens), icon: Layers3, note: missingCache > 0 ? `Not reported for ${number(missingCache)} requests` : "Reused from the prompt cache" },
    { label: "Output tokens", value: number(usage.outputTokens), icon: ArrowUp, note: "Generated by your models" },
  ]
  return <>
    <div className="mt-7 flex flex-wrap items-end gap-x-4 gap-y-1"><p className="font-heading text-4xl tabular-nums" data-usage="total">{number(usage.totalTokens)}</p><p className="pb-1 text-sm text-slate-500">total tokens · {number(usage.requests)} {usage.requests === 1 ? "request" : "requests"}</p></div>
    <div className="mt-6 grid gap-5 min-[1100px]:grid-cols-3">{metrics.map(({ label, value, icon: Icon, note }) => <div key={label} className="border-l-2 border-blue-200 pl-4 dark:border-blue-900"><p className="flex items-center gap-2 text-sm text-slate-500"><Icon className="size-4" />{label}</p><p className="mt-2 font-heading text-2xl tabular-nums" data-usage={label}>{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div>)}</div>
    <div className="mt-6 grid gap-4 border-t border-slate-200 pt-5 min-[900px]:grid-cols-2 dark:border-slate-750">
      <div><p className="flex items-center gap-2 text-sm text-slate-500"><Gauge className="size-4" />Generation speed</p><p className="mt-2 text-xl tabular-nums" data-usage="speed">{usage.tokensPerSecond === null ? "—" : `${decimal(usage.tokensPerSecond)} tokens/s`}</p></div>
      <div><p className="flex items-center gap-2 text-sm text-slate-500"><Timer className="size-4" />Time to first token</p><p className="mt-2 text-xl tabular-nums" data-usage="ttft">{usage.timeToFirstTokenMs === null ? "—" : usage.timeToFirstTokenMs < 1000 ? `${decimal(usage.timeToFirstTokenMs)} ms` : `${decimal(usage.timeToFirstTokenMs / 1000)} s`}</p></div>
    </div>
    {usage.requests === 0 && <p className="mt-5 text-sm text-slate-500">No requests in this view yet. Usage appears as your connected tools run models.</p>}
    {(usage.incompleteRequests > 0 || usage.recordingFailures > 0) && <p role="status" className="mt-5 text-sm text-amber-700 dark:text-amber-400">Totals are partial.{usage.incompleteRequests > 0 && ` ${number(usage.incompleteRequests)} requests ended without complete usage evidence.`}{usage.recordingFailures > 0 && ` ${number(usage.recordingFailures)} usage records could not be saved this session.`}</p>}
    <details className="mt-5 text-xs text-slate-500"><summary className="cursor-pointer">About these numbers</summary><p className="mt-2 leading-relaxed">Input includes cached input; total is input plus output. Speed is weighted by generation time across {number(usage.speedSamples)} measured requests. First-token time is averaged across {number(usage.latencySamples)} measured requests. Native timings are used when available; other streaming timings are measured at the service. Missing measurements are excluded, not counted as zero. History covers local requests through Magnitude{usage.since === null ? "." : ` since ${new Date(usage.since).toLocaleDateString()}.`}</p></details>
  </>
}
