/**
 * Measures the system prompt token overhead for CodingAgentChat.
 * 
 * Makes a minimal streaming LLM call and captures the actual
 * input token count from the raw Anthropic response.
 * 
 * Usage: bun run scripts/measure-system-prompt.ts
 */

import { b, Collector } from '@magnitudedev/llm-core'
import { join } from 'path'
import { mkdir } from 'fs/promises'
import { getSystemPrompt } from '../src/roles'
import { join } from 'path'
import { mkdir } from 'fs/promises'

type AnthropicUsage = {
  input_tokens: number
  cache_creation_input_tokens: number
  cache_read_input_tokens: number
  output_tokens: number
}

async function main() {
  const collector = new Collector('system-prompt-measure')
  const minimalMessages = [{ role: 'user' as const, content: '.' }]

  const stream = b.stream.CodingAgentChat(getSystemPrompt(), minimalMessages, false, { collector })
  
  try {
    for await (const chunk of stream) {}
    await stream.getFinalResponse()
  } catch (e) {
    // parse errors are fine
  }

  // Parse the raw Anthropic response for full usage
  const rawUsage = collector.last?.calls.at(-1)?.httpResponse?.body.json().usage as AnthropicUsage | undefined

  if (!rawUsage) {
    console.error('ERROR: Could not extract usage from raw response')
    console.error('Collector usage:', String(collector.usage))
    process.exit(1)
  }

  console.log('Raw Anthropic usage:')
  console.log('  input_tokens: ' + rawUsage.input_tokens)
  console.log('  cache_creation_input_tokens: ' + rawUsage.cache_creation_input_tokens)
  console.log('  cache_read_input_tokens: ' + rawUsage.cache_read_input_tokens)

  const totalInputTokens = rawUsage.input_tokens
    + (rawUsage.cache_creation_input_tokens ?? 0)
    + (rawUsage.cache_read_input_tokens ?? 0)

  console.log('  total input tokens: ' + totalInputTokens)

  // Subtract ~1 token for the minimal "." user message
  const systemPromptTokens = totalInputTokens - 1

  console.log('System prompt tokens (total - 1): ' + systemPromptTokens)

  const lines = [
    '/**',
    ' * Auto-generated by scripts/measure-system-prompt.ts',
    ' * Do not edit manually — run: bun run scripts/measure-system-prompt.ts',
    ' *',
    ' * Last generated: ' + new Date().toISOString(),
    ' */',
    '',
    '/** Actual token count of the BAML system prompt + few-shot template overhead, measured via Collector */',
    'export const SYSTEM_PROMPT_TOKENS = ' + systemPromptTokens,
    ''
  ]

  const outDir = join(__dirname, '..', 'src', 'generated')
  const outPath = join(outDir, 'system-prompt-size.ts')

  await mkdir(outDir, { recursive: true })
  await Bun.write(outPath, lines.join('\n'))
  console.log('Written to ' + outPath)
}

main().catch(console.error)
