import { resolve } from 'path'

const PROJECT_ROOT = resolve(import.meta.dir, '../..')
const SOURCE_PACKAGE_JSON = resolve(PROJECT_ROOT, 'packages/cli/package.json')
const OUTPUT_FILE = resolve(PROJECT_ROOT, 'cli/src/version.generated.ts')

async function main() {
  const packageJson = JSON.parse(await Bun.file(SOURCE_PACKAGE_JSON).text()) as { version?: string }

  if (!packageJson.version) {
    throw new Error(`No version found in ${SOURCE_PACKAGE_JSON}`)
  }

  const contents =
    `// Generated by cli/scripts/generate-version.ts\n` +
    `// Source: packages/cli/package.json\n` +
    `export const CLI_VERSION = ${JSON.stringify(packageJson.version)}\n`

  await Bun.write(OUTPUT_FILE, contents)
}

await main()
