import { resolve } from "path"

const PROJECT_ROOT = resolve(import.meta.dir, "..", "..", "..")
const SOURCE_PACKAGE_JSON = resolve(PROJECT_ROOT, "packages/cli/package.json")
const OUTPUT_FILE = resolve(PROJECT_ROOT, "packages/version/src/version.generated.ts")

const isDev = process.argv.includes("--dev")

const readGitShortHash = (): string => {
  const proc = Bun.spawnSync(["git", "rev-parse", "--short", "HEAD"], {
    cwd: PROJECT_ROOT,
    stdout: "pipe",
    stderr: "ignore",
  })
  if (proc.exitCode !== 0) return "unknown"
  return proc.stdout.toString().trim() || "unknown"
}

async function main() {
  const packageJson = JSON.parse(await Bun.file(SOURCE_PACKAGE_JSON).text()) as { version?: string }

  if (!packageJson.version) {
    throw new Error(`No version found in ${SOURCE_PACKAGE_JSON}`)
  }

  const version = isDev
    ? `${packageJson.version}+dev.${readGitShortHash()}.${Date.now()}`
    : packageJson.version

  const contents =
    `// Generated by packages/version/scripts/generate-version.ts\n` +
    `// Source: packages/cli/package.json\n` +
    `export const MAGNITUDE_VERSION = ${JSON.stringify(version)}\n`

  await Bun.write(OUTPUT_FILE, contents)
}

await main()
