import { mkdir, readFile, writeFile } from "node:fs/promises"
import { homedir } from "node:os"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const PROJECT_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..")
const SOURCE_PACKAGE_JSON = resolve(PROJECT_ROOT, "packages/launcher/package.json")
/** The one committed release record. Read as data; this package never imports release code. */
const RELEASE_PLAN_FILE = resolve(PROJECT_ROOT, "packages/release/release-plan.json")
const VERSION_OUTPUT_FILE = resolve(PROJECT_ROOT, "packages/version/src/version.generated.ts")
const RPC_OUTPUT_FILE = resolve(PROJECT_ROOT, "packages/acn-protocol/src/rpc-version.ts")
const DEVELOPMENT_COUNTER_FILE = resolve(
  homedir(),
  ".magnitude/acn/development-revision-counter",
)
export const DEVELOPMENT_COUNTER_ENVIRONMENT_VARIABLE =
  "MAGNITUDE_DEV_REVISION_COUNTER"

const isDev = process.argv.includes("--dev")

interface ReleaseIdentity {
  readonly revision: number
  readonly rpcVersion: number
}

const readGitShortHash = (): string => {
  const proc = Bun.spawnSync(["git", "rev-parse", "--short", "HEAD"], {
    cwd: PROJECT_ROOT,
    stdout: "pipe",
    stderr: "ignore",
  })
  if (proc.exitCode !== 0) return "unknown"
  return proc.stdout.toString().trim() || "unknown"
}

const developmentVersion = (
  baseVersion: string,
  counter: number,
): string => `${baseVersion}+dev.${readGitShortHash()}.${counter}`

const isAllocation = (value: unknown): value is number =>
  Number.isSafeInteger(value) && (value as number) > 0

const readReleaseIdentity = async (): Promise<ReleaseIdentity> => {
  const plan = JSON.parse(await readFile(RELEASE_PLAN_FILE, "utf8")) as {
    revision?: unknown
    rpc?: { version?: unknown }
  }
  if (!isAllocation(plan.revision) || !isAllocation(plan.rpc?.version)) {
    throw new Error("packages/release/release-plan.json has no valid revision and RPC allocation")
  }
  return { revision: plan.revision, rpcVersion: plan.rpc.version }
}

export const nextDevelopmentCounter = async (
  path: string = DEVELOPMENT_COUNTER_FILE,
): Promise<number> => {
  await mkdir(dirname(path), { recursive: true, mode: 0o700 })
  let current = 0
  try {
    current = Number((await readFile(path, "utf8")).trim())
    if (!Number.isSafeInteger(current) || current < 0) {
      throw new Error("The local ACN development revision counter is malformed")
    }
  } catch (error) {
    if (!(error instanceof Error && "code" in error && error.code === "ENOENT")) throw error
  }
  const next = current + 1
  if (!Number.isSafeInteger(next)) {
    throw new Error("The local ACN development revision counter is exhausted")
  }
  await writeFile(path, `${next}\n`, { mode: 0o600 })
  return next
}

export const resolveDevelopmentCounter = async (
  override: string | undefined =
    process.env[DEVELOPMENT_COUNTER_ENVIRONMENT_VARIABLE],
  path: string = DEVELOPMENT_COUNTER_FILE,
): Promise<number> => {
  if (override === undefined) return nextDevelopmentCounter(path)

  const value = Number(override.trim())
  if (override.trim().length === 0 || !Number.isSafeInteger(value) || value < 0) {
    throw new Error(
      `${DEVELOPMENT_COUNTER_ENVIRONMENT_VARIABLE} must be a non-negative safe integer`,
    )
  }
  return value
}

export interface GeneratedIdentity {
  readonly cliVersion: string
  readonly revision: number
  readonly rpcVersion: number
  readonly devCounter?: number
}

const rpcVersionSource = (rpcVersion: number): string =>
  `// Generated by packages/version/scripts/generate-version.ts from packages/release/release-plan.json. Do not edit.\n` +
  `export const MAGNITUDE_RPC_VERSION = ${rpcVersion}\n`

/** Write every generated identity constant. Release preparation calls this with its allocation. */
export const generateVersionFiles = async ({
  cliVersion,
  revision: allocated,
  rpcVersion,
  devCounter,
}: GeneratedIdentity): Promise<void> => {
  const version = devCounter === undefined
    ? cliVersion
    : developmentVersion(cliVersion, devCounter)
  const revision = allocated + (devCounter ?? 0)
  if (!Number.isSafeInteger(revision)) {
    throw new Error("The generated ACN coordination revision exceeds the safe integer range")
  }
  const contents =
    `// Generated by packages/version/scripts/generate-version.ts\n` +
    `// Source: packages/launcher/package.json and packages/release/release-plan.json\n` +
    (devCounter === undefined
      ? ""
      : `// Local development counter: ${devCounter}\n`) +
    `export const MAGNITUDE_VERSION = ${JSON.stringify(version)}\n` +
    `export const ACN_COORDINATION_REVISION = ${revision}\n`
  await Bun.write(VERSION_OUTPUT_FILE, contents)
  await Bun.write(RPC_OUTPUT_FILE, rpcVersionSource(rpcVersion))
}

/** The RPC version currently generated on disk, for verification against the plan. */
export const readGeneratedRpcVersion = async (): Promise<number | undefined> => {
  try {
    const match = /^export const MAGNITUDE_RPC_VERSION = (\d+)$/m.exec(
      await readFile(RPC_OUTPUT_FILE, "utf8"),
    )
    return match === null ? undefined : Number(match[1])
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") return undefined
    throw error
  }
}

async function main() {
  const packageJson = JSON.parse(await Bun.file(SOURCE_PACKAGE_JSON).text()) as { version?: string }

  if (!packageJson.version) {
    throw new Error(`No version found in ${SOURCE_PACKAGE_JSON}`)
  }

  const identity = await readReleaseIdentity()
  const devCounter = isDev ? await resolveDevelopmentCounter() : undefined
  await generateVersionFiles({
    cliVersion: packageJson.version,
    revision: identity.revision,
    rpcVersion: identity.rpcVersion,
    devCounter,
  })
}

if (import.meta.main) await main()
