import { resolve } from "path"
import { link, mkdir, readFile, unlink, writeFile } from "node:fs/promises"

const PROJECT_ROOT = resolve(import.meta.dir, "..", "..", "..")
const SOURCE_PACKAGE_JSON = resolve(PROJECT_ROOT, "packages/cli/package.json")
const OUTPUT_FILE = resolve(PROJECT_ROOT, "packages/version/src/version.generated.ts")
const OUTPUT_RELATIVE = "packages/version/src/version.generated.ts"

const isDev = process.argv.includes("--dev")

const readGitShortHash = (): string => {
  const proc = Bun.spawnSync(["git", "rev-parse", "--short", "HEAD"], {
    cwd: PROJECT_ROOT,
    stdout: "pipe",
    stderr: "ignore",
  })
  if (proc.exitCode !== 0) return "unknown"
  return proc.stdout.toString().trim() || "unknown"
}

const gitOutput = (args: ReadonlyArray<string>): Uint8Array => {
  const proc = Bun.spawnSync(["git", ...args], {
    cwd: PROJECT_ROOT,
    stdout: "pipe",
    stderr: "ignore",
  })
  return proc.exitCode === 0 ? proc.stdout : new Uint8Array()
}

const developmentFingerprint = async (): Promise<string> => {
  const hash = new Bun.CryptoHasher("sha256")
  hash.update(readGitShortHash())
  hash.update(gitOutput([
    "diff",
    "--no-ext-diff",
    "--binary",
    "HEAD",
    "--",
    ".",
    `:(exclude)${OUTPUT_RELATIVE}`,
  ]))
  const untracked = new TextDecoder().decode(gitOutput([
    "ls-files",
    "--others",
    "--exclude-standard",
    "-z",
  ])).split("\0").filter((path) => path.length > 0 && path !== OUTPUT_RELATIVE).sort()
  for (const relative of untracked) {
    hash.update(relative)
    hash.update(await Bun.file(resolve(PROJECT_ROOT, relative)).arrayBuffer())
  }
  return hash.digest("hex").slice(0, 16)
}

const developmentVersion = async (
  baseVersion: string,
  fingerprint: string,
): Promise<string> => {
  const gitPath = new TextDecoder().decode(gitOutput([
    "rev-parse",
    "--git-path",
    "magnitude-dev-versions",
  ])).trim()
  const cacheDirectory = resolve(PROJECT_ROOT, gitPath || ".git/magnitude-dev-versions")
  const cachePath = resolve(cacheDirectory, fingerprint)
  const candidate = `${baseVersion}+dev.${readGitShortHash()}.${Date.now()}`
  const temporary = `${cachePath}.${process.pid}.${Date.now()}.tmp`
  await mkdir(cacheDirectory, { recursive: true })
  await writeFile(temporary, `${candidate}\n`, { flag: "wx", mode: 0o600 })
  try {
    await link(temporary, cachePath)
    return candidate
  } catch (error) {
    if (!(error instanceof Error && "code" in error && error.code === "EEXIST")) throw error
    return (await readFile(cachePath, "utf8")).trim()
  } finally {
    await unlink(temporary).catch(() => undefined)
  }
}

async function main() {
  const packageJson = JSON.parse(await Bun.file(SOURCE_PACKAGE_JSON).text()) as { version?: string }

  if (!packageJson.version) {
    throw new Error(`No version found in ${SOURCE_PACKAGE_JSON}`)
  }

  const fingerprint = isDev ? await developmentFingerprint() : undefined
  const version = isDev
    ? await developmentVersion(packageJson.version, fingerprint!)
    : packageJson.version

  const contents =
    `// Generated by packages/version/scripts/generate-version.ts\n` +
    `// Source: packages/cli/package.json\n` +
    (fingerprint === undefined ? "" : `// Development fingerprint: ${fingerprint}\n`) +
    `export const MAGNITUDE_VERSION = ${JSON.stringify(version)}\n`

  await Bun.write(OUTPUT_FILE, contents)
}

await main()
