export { createMagnitudeProvider, fetchBalance, PROVIDER_ID, type MagnitudeProviderInstance, type MagnitudeClientConfig, type FetchBalanceOptions, WebSearchError, MagnitudeClientError } from "./provider"
export { createMagnitudeCatalog, toMagnitudeModelInfo } from "./catalog"
export { createMagnitudeCompatibleSpec, type MagnitudeCallOptions, type MagnitudeModelSpec, type MagnitudeCompatibleSpecConfig } from "./models"
export { classifyMagnitudeRejectedResponse, tryParseErrorBody, type ParsedMagnitudeApiError } from "./errors"
export { MagnitudeModelListResponseSchema, MagnitudeRawModelSchema } from "./contract"
export type { MagnitudeModelInfo, MagnitudeRawModel, ModelListResponse, ToolChoice, MagnitudeAdditionalOptions, MagnitudeApiError, MagnitudeErrorType, MagnitudeErrorCode, MagnitudeErrorDetails, InsufficientCreditsDetails, ReasoningEffort, ModelPricingInfo } from "./contract"
export type { BalanceResponse, UsagePeriod } from "./usage"
export type { ModelProfile } from "@magnitudedev/ai"
export { toModelProfile } from "@magnitudedev/ai"
