import { CommandExecutor } from "@effect/platform"
import { BunContext } from "@effect/platform-bun"
import { Effect, Schema } from "effect"
import { createHash, generateKeyPairSync } from "node:crypto"
import { mkdtemp, readFile, readdir, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { afterEach, describe, expect, it, vi } from "vitest"
import { PublisherKeyId, signUpdateManifest, UpdateManifest } from "../../../release/src/hosted-update/manifest"
import { makeLinuxPackageInstaller } from "./linux-update-package"
import { GuardedCommand } from "@magnitudedev/utils/guarded-command"

const uid = process.getuid!()
afterEach(() => vi.unstubAllGlobals())

const formats = [
  { package: "deb", arch: "arm64", version: "2.0.0", current: "1.0.0", query: "/usr/bin/dpkg-deb", install: "/usr/bin/apt-get", installArgs: ["install", "--yes", "--no-remove", "--"],
    identity: (name: string) => `${name}\t2.0.0-42\tarm64` },
  { package: "pacman", arch: "x64", version: "2.0.0-beta.1", current: "1.0.0-beta.1", query: "/usr/bin/bsdtar", install: "/usr/bin/pacman", installArgs: ["--upgrade", "--noconfirm", "--"],
    identity: (name: string) => `# Generated by Magnitude release packaging\npkgname = ${name}\npkgbase = ${name}\npkgver = 2.0.0beta.1-42\narch = x86_64\ndepend = glibc\n` },
] as const

describe.each(formats)("privileged Linux $package package verification", format => {
  it.each(["valid", "hash", "signature", "target", "downgrade", "identity", "package-manager"] as const)("checks %s before admitting installation", async scenario => {
    vi.stubGlobal("process", { ...process, platform: "linux", arch: format.arch, getuid: () => 0 })
    const otherArch = format.arch === "arm64" ? "x64" : "arm64"
    const directory = await mkdtemp(join(tmpdir(), "linux-package-verification-"))
    const archive = join(directory, `update.${format.package}`)
    const bytes = Buffer.from("publisher-owned package bytes")
    await writeFile(archive, bytes)
    const key = generateKeyPairSync("ed25519")
    const manifest = Schema.decodeUnknownSync(UpdateManifest)({ protocol: 1, tag: `@magnitudedev/cli@${format.version}`, version: format.version, commit: "a".repeat(40), artifact: {
      id: `desktop-linux-${format.arch}-gnu-${format.package}`, target: { os: "linux", arch: scenario === "target" ? otherArch : format.arch, package: format.package },
      filename: `magnitude.${format.package}`, bytes: bytes.length, sha256: createHash("sha256").update(bytes).digest("hex"),
    } })
    const envelope = await Effect.runPromise(signUpdateManifest(manifest, key.privateKey))
    if (scenario === "hash") await writeFile(archive, Buffer.alloc(bytes.length))
    let queried = false
    let installed = false
    const executor = CommandExecutor.makeExecutor(command => Effect.gen(function* () {
      throw new Error(`Unexpected process start: ${command._tag}`)
    }))
    try {
      const result = await Effect.runPromise(Effect.gen(function* () {
        const installer = yield* makeLinuxPackageInstaller({ package: format.package, callerUid: uid, currentVersion: scenario === "downgrade" ? "3.0.0" : format.current,
          trustedPublishers: new Map([["test", scenario === "signature" ? generateKeyPairSync("ed25519").publicKey : key.publicKey]]) })
        return yield* installer.install({ release: envelope.release, packagePath: archive }).pipe(Effect.either)
      }).pipe(Effect.provideService(CommandExecutor.CommandExecutor, {
        ...executor,
        string: command => Effect.promise(async () => {
          queried = true
          expect(command._tag).toBe("StandardCommand")
          if (command._tag !== "StandardCommand") throw new Error("Expected native package query")
          expect(command.command).toBe(format.query)
          const queriedPath = format.package === "pacman" ? command.args.at(-2)! : command.args.at(-1)!
          expect(queriedPath).not.toBe(archive)
          expect(await readFile(queriedPath)).toEqual(bytes)
          return format.identity(scenario === "identity" ? "another-package" : "magnitude-desktop")
        }),
      }), Effect.provideService(GuardedCommand, {
        run: (command, args, environment) => Effect.sync(() => {
          installed = true
          expect(command).toBe(format.install)
          expect(args.slice(0, format.installArgs.length)).toEqual(format.installArgs)
          if (format.package === "deb") expect(environment.DEBIAN_FRONTEND).toBe("noninteractive")
          return { code: scenario === "package-manager" ? 100 : 0, stdout: "", stderr: "" }
        }),
      }), Effect.provide(BunContext.layer)))
      expect(result._tag).toBe(scenario === "valid" ? "Right" : "Left")
      expect(queried).toBe(["valid", "identity", "package-manager"].includes(scenario))
      expect(installed).toBe(["valid", "package-manager"].includes(scenario))
      expect(await readdir(directory)).toEqual([`update.${format.package}`])
    } finally { await rm(directory, { recursive: true, force: true }) }
  })
})
