schema_version = 1

[llama_cpp_rs]
checkout_path = "native/llama-cpp-rs"
crate_path = "native/llama-cpp-rs/llama-cpp-2"
repository = "https://github.com/magnitudedev/llama-cpp-rs.git"
upstream_repository = "https://github.com/utilityai/llama-cpp-rs"
revision = "aa338b838b1986d07d7f8eafd209d55f370d8bee"
release = "0.1.151"

[llama_cpp]
checkout_path = "native/llama-cpp-rs/llama-cpp-sys-2/llama.cpp"
repository = "https://github.com/ggml-org/llama.cpp"
revision = "178a6c44937154dc4c4eff0d166f4a044c4fceba"
