// Shared geometry for content and its loading presentation. Keep responsive changes here.
export const pageLayout = {
  hardwarePhoto: "min-w-0 overflow-hidden rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-900",
  hardwareGrid: "grid-cols-[140px_minmax(0,1fr)] min-[1000px]:grid-cols-[220px_minmax(0,1fr)]",
  recommendationRow: "flex min-h-16 min-w-0 w-full items-center gap-3 rounded-xl border px-3 py-4 text-left",
  modelCard: "rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-750 dark:bg-slate-850",
  modelRow: "grid items-center gap-4 lg:grid-cols-[minmax(0,1fr)_auto]",
  recommendations: "grid overflow-hidden rounded-2xl border border-slate-200 bg-white dark:border-slate-750 dark:bg-slate-850 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]",
  recommendationList: "min-w-0 space-y-2 p-3",
  recommendationPane: "min-w-0 border-t border-slate-200 p-5 dark:border-slate-750 lg:border-l lg:border-t-0",
  recommendationToolbar: "mb-4 flex flex-wrap items-center justify-between gap-3",
  modelRadar: "mx-auto my-3 aspect-[360/270] w-full max-w-sm",
  statusStack: "mt-7 space-y-6",
  statusHero: "rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-750 dark:bg-slate-850",
  card: "rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-750 dark:bg-slate-850",
  settingsCard: "mt-6 rounded-lg border border-slate-300 bg-white px-5 py-5 dark:border-slate-750 dark:bg-slate-850",
  pageTitle: "shrink-0 font-heading text-[28px] font-semibold tracking-tight",
  modelHeader: "mb-5 flex flex-wrap items-center justify-between gap-x-4 gap-y-2",
  modelSearch: "min-w-40 flex-1 sm:max-w-xs",
  catalogToolbar: "mb-5 flex flex-wrap items-center justify-between gap-3",
  hardware: "relative my-6 overflow-hidden rounded-2xl border border-blue-200 bg-gradient-to-br from-blue-50 via-white to-slate-100 p-6 dark:border-slate-700 dark:from-slate-800 dark:via-slate-850 dark:to-slate-900",
  harnessCard: "rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-750 dark:bg-slate-850",
  harnessGrid: "grid grid-cols-1 items-start gap-5",
  usageTokens: "grid gap-5 min-[1100px]:grid-cols-3",
  usageTiming: "grid gap-5 min-[1100px]:grid-cols-3",
} as const
